### ISSUE TITLE
Drupal 8 twig js render file

### ISSUE THREAD

**Issue by twilderan** [twigjs/twig.js#658]
Hi.

I faced some issues with twig.js in Drupal 8. We need to use it with twig templates.
I added twig.js library, included twig.min.js file in module.libraries.yml
```
twig.js:
  version: VERSION
  js:
    js/twig/twig.min.js: {}
  dependencies:
    - core/jquery
    - core/jquery.ui
    - core/jquery.ui.widget
```

Troubles appear when i try to render twig file 
```
      Twig.renderFile('./path/to/someFile.twig', {foo:'bar'}, function (err, html) {
        return console.log(html); // compiled string
      });
```
i get some errors
![image](https://user-images.githubusercontent.com/29509266/64849613-6dbc5c00-d61c-11e9-88f3-e9012b6abd08.png)

Maybe someone knows what's wrong?

P.S.  This code works.
```
      var template = Twig.twig({
        data: '{{ baked_good }}'
      });
      console.log(template.render({baked_good: this.attrs['content']}));
```
